---
name: WWW-Search-MSN
version: 0.0105
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: backend for searching search.msn.com
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
requires:
  Encode: 0
  HTML::TreeBuilder: 0
  Scalar::Util: 0
  Test::More: 0
  WWW::Search: 2.523
  WWW::Search::Test: 2.265
provides:
  WWW::Search::MSN:
    file: lib/WWW/Search/MSN.pm
    version: 0.0105
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
